CREATE TABLE IF NOT EXISTS `devchacha_farming` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) DEFAULT NULL,
  `plantname` varchar(50) DEFAULT NULL,
  `data` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert tools into VORP items database table
INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES
('emptybucket', 'Empty Bucket', 5, 1, 'item_standard', 1),
('fullbucket', 'Full Bucket', 5, 1, 'item_standard', 1),
('shovel', 'Shovel', 5, 1, 'item_standard', 1);

-- Insert seeds into VORP items database table
INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES
('alaskan_ginseng_seed', 'Alaskan Ginseng Seed', 100, 1, 'item_standard', 1),
('american_ginseng_seed', 'American Ginseng Seed', 100, 1, 'item_standard', 1),
('hop_seed', 'Hop Seed', 100, 1, 'item_standard', 1),
('black_currant_seed', 'Black Currant Seed', 100, 1, 'item_standard', 1),
('creekplum_seed', 'Creekplum Seed', 100, 1, 'item_standard', 1),
('crows_garlic_seed', 'Crows Garlic Seed', 100, 1, 'item_standard', 1),
('indian_tobbaco_seed', 'Indian Tobacco Seed', 100, 1, 'item_standard', 1),
('milk_weed_seed', 'Milk Weed Seed', 100, 1, 'item_standard', 1),
('oleander_sage_seed', 'Oleander Sage Seed', 100, 1, 'item_standard', 1),
('parasol_mushroom_seed', 'Parasol Mushroom Seed', 100, 1, 'item_standard', 1),
('prairie_poppy_seed', 'Prairie Poppy Seed', 100, 1, 'item_standard', 1),
('red_raspberry_seed', 'Red Raspberry Seed', 100, 1, 'item_standard', 1),
('red_sage_seed', 'Red Sage Seed', 100, 1, 'item_standard', 1),
('carrot_seed', 'Carrot Seed', 100, 1, 'item_standard', 1),
('wild_mint_seed', 'Wild Mint Seed', 100, 1, 'item_standard', 1),
('wintergreen_berry_seed', 'Wintergreen Berry Seed', 100, 1, 'item_standard', 1),
('yarrow_seed', 'Yarrow Seed', 100, 1, 'item_standard', 1),
('corn_seed', 'Corn Seed', 100, 1, 'item_standard', 1),
('apple_seed', 'Apple Seed', 100, 1, 'item_standard', 1),
('potato_seed', 'Potato Seed', 100, 1, 'item_standard', 1),
('wheat_seed', 'Wheat Seed', 100, 1, 'item_standard', 1),
('pumpkin_seed', 'Pumpkin Seed', 100, 1, 'item_standard', 1),
('cocoaseeds', 'Cocoa Seed', 100, 1, 'item_standard', 1),
('coffee_seed', 'Coffee Seed', 100, 1, 'item_standard', 1),
('pepper_seed', 'Pepper Seed', 100, 1, 'item_standard', 1),
('blood_flower_seed', 'Blood Flower Seed', 100, 1, 'item_standard', 1),
('choc_daisy_seed', 'Choc Daisy Seed', 100, 1, 'item_standard', 1),
('hummingbird_sage_seed', 'Hummingbird Sage Seed', 100, 1, 'item_standard', 1),
('tobacco_seed', 'Tobacco Seed', 100, 1, 'item_standard', 1),
('cherry_seed', 'Cherry Seed', 100, 1, 'item_standard', 1),
('lemon_seed', 'Lemon Seed', 100, 1, 'item_standard', 1),
('barley_seed', 'Barley Seed', 100, 1, 'item_standard', 1),
('banana_seed', 'Banana Seed', 100, 1, 'item_standard', 1),
('Creeking_Thyme_Seed', 'Creeking Thyme Seed', 100, 1, 'item_standard', 1),
('English_Mace_Seed', 'English Mace Seed', 100, 1, 'item_standard', 1),
('Oregano_Seed', 'Oregano Seed', 100, 1, 'item_standard', 1),
('teaseeds', 'Tea Seed', 100, 1, 'item_standard', 1),
('sugarcaneseed', 'Sugarcane Seed', 100, 1, 'item_standard', 1),
('peachseeds', 'Peach Seed', 100, 1, 'item_standard', 1),
('tomato_seed', 'Tomato Seed', 100, 1, 'item_standard', 1),
('lettuce_seed', 'Lettuce Seed', 100, 1, 'item_standard', 1),
('broccoli_seed', 'Broccoli Seed', 100, 1, 'item_standard', 1),
('agarita_seed', 'Agarita Seed', 100, 1, 'item_standard', 1),
('bay_bolete_seed', 'Bay Bolete Seed', 100, 1, 'item_standard', 1),
('blackberry_seed', 'Blackberry Seed', 100, 1, 'item_standard', 1),
('evergreen_huckleberry_seed', 'Evergreen Huckleberry Seed', 100, 1, 'item_standard', 1),
('strawberry_seed', 'Strawberry Seed', 100, 1, 'item_standard', 1),
('onion_seed', 'Onion Seed', 100, 1, 'item_standard', 1),
('artichoke_seed', 'Artichoke Seed', 100, 1, 'item_standard', 1),
('beans_seed', 'Beans Seed', 100, 1, 'item_standard', 1),
('beetroot_seed', 'Beetroot Seed', 100, 1, 'item_standard', 1),
('cabbage_seed', 'Cabbage Seed', 100, 1, 'item_standard', 1),
('celery_seed', 'Celery Seed', 100, 1, 'item_standard', 1),
('cucumber_seed', 'Cucumber Seed', 100, 1, 'item_standard', 1),
('grapes_seed', 'Grapes Seed', 100, 1, 'item_standard', 1),
('lime_seed', 'Lime Seed', 100, 1, 'item_standard', 1),
('mango_seed', 'Mango Seed', 100, 1, 'item_standard', 1),
('orange_seed', 'Orange Seed', 100, 1, 'item_standard', 1),
('pear_seed', 'Pear Seed', 100, 1, 'item_standard', 1),
('watermelon_seed', 'Watermelon Seed', 100, 1, 'item_standard', 1),
('peanut_seed', 'Peanut Seed', 100, 1, 'item_standard', 1),
('rice_seed', 'Rice Seed', 100, 1, 'item_standard', 1),
('squash_seed', 'Squash Seed', 100, 1, 'item_standard', 1);

-- Insert harvested crops into VORP items database table
INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES
('alaskan_ginseng', 'Alaskan Ginseng', 200, 1, 'item_standard', 0),
('american_ginseng', 'American Ginseng', 200, 1, 'item_standard', 0),
('hop', 'Hop', 200, 1, 'item_standard', 0),
('black_currant', 'Black Currant', 200, 1, 'item_standard', 1),
('creekplum', 'Creekplum', 200, 1, 'item_standard', 0),
('crows_garlic', 'Crows Garlic', 200, 1, 'item_standard', 0),
('indian_tobacco', 'Indian Tobacco', 200, 1, 'item_standard', 0),
('milk_weed', 'Milk Weed', 200, 1, 'item_standard', 0),
('oleander_sage', 'Oleander Sage', 200, 1, 'item_standard', 0),
('parasol_mushroom', 'Parasol Mushroom', 200, 1, 'item_standard', 0),
('prairie_poppy', 'Prairie Poppy', 200, 1, 'item_standard', 0),
('red_raspberry', 'Red Raspberry', 200, 1, 'item_standard', 1),
('red_sage', 'Red Sage', 200, 1, 'item_standard', 0),
('carrot', 'Carrot', 200, 1, 'item_standard', 0),
('wild_mint', 'Wild Mint', 200, 1, 'item_standard', 0),
('wintergreen_berry', 'Wintergreen Berry', 200, 1, 'item_standard', 1),
('yarrow', 'Yarrow', 200, 1, 'item_standard', 0),
('corn', 'Corn', 200, 1, 'item_standard', 1),
('apple', 'Apple', 200, 1, 'item_standard', 1),
('potato', 'Potato', 200, 1, 'item_standard', 1),
('wheat', 'Wheat', 200, 1, 'item_standard', 0),
('pumpkin', 'Pumpkin', 200, 1, 'item_standard', 0),
('cocoabeans', 'Cocoa Beans', 200, 1, 'item_standard', 0),
('coffeebeans', 'Coffee Beans', 200, 1, 'item_standard', 0),
('pimenta', 'Pimenta', 200, 1, 'item_standard', 0),
('Blood_Flower', 'Blood Flower', 200, 1, 'item_standard', 0),
('Choc_Daisy', 'Choc Daisy', 200, 1, 'item_standard', 0),
('Hummingbird_Sage', 'Hummingbird Sage', 200, 1, 'item_standard', 0),
('tobacco', 'Tobacco', 200, 1, 'item_standard', 0),
('consumable_peach', 'Peach', 200, 1, 'item_standard', 1),
('cherry', 'Cherry', 200, 1, 'item_standard', 1),
('lemon', 'Lemon', 200, 1, 'item_standard', 1),
('barley', 'Barley', 200, 1, 'item_standard', 0),
('banana', 'Banana', 200, 1, 'item_standard', 1),
('Creeking_Thyme', 'Creeking Thyme', 200, 1, 'item_standard', 0),
('English_Mace', 'English Mace', 200, 1, 'item_standard', 0),
('Oregano', 'Oregano', 200, 1, 'item_standard', 0),
('tealeaf', 'Tea Leaf', 200, 1, 'item_standard', 0),
('cana', 'Sugarcane', 200, 1, 'item_standard', 0),
('tomato', 'Tomato', 200, 1, 'item_standard', 1),
('lettuce', 'Lettuce', 200, 1, 'item_standard', 1),
('broccoli', 'Broccoli', 200, 1, 'item_standard', 1),
('agarita', 'Agarita', 200, 1, 'item_standard', 0),
('bay_bolete', 'Bay Bolete', 200, 1, 'item_standard', 0),
('blackberry', 'Blackberry', 200, 1, 'item_standard', 1),
('evergreen_huckleberry', 'Evergreen Huckleberry', 200, 1, 'item_standard', 0),
('strawberry', 'Strawberry', 200, 1, 'item_standard', 1),
('onion', 'Onion', 200, 1, 'item_standard', 1),
('artichoke', 'Artichoke', 200, 1, 'item_standard', 1),
('beans', 'Beans', 200, 1, 'item_standard', 1),
('beetroot', 'Beetroot', 200, 1, 'item_standard', 1),
('cabbage', 'Cabbage', 200, 1, 'item_standard', 1),
('celery', 'Celery', 200, 1, 'item_standard', 1),
('cucumber', 'Cucumber', 200, 1, 'item_standard', 1),
('grapes', 'Grapes', 200, 1, 'item_standard', 1),
('lime', 'Lime', 200, 1, 'item_standard', 1),
('mango', 'Mango', 200, 1, 'item_standard', 1),
('orange', 'Orange', 200, 1, 'item_standard', 1),
('pear', 'Pear', 200, 1, 'item_standard', 1),
('watermelon', 'Watermelon', 200, 1, 'item_standard', 1),
('raw_peanuts', 'Raw Peanuts', 200, 1, 'item_standard', 1),
('rice', 'Rice', 200, 1, 'item_standard', 1),
('squash', 'Squash', 200, 1, 'item_standard', 1);
